version: '3.3'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: matheus

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


    
