version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "tic_tac_toe"
      MYSQL_DATABASE: "tic_tac_toe"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
